### ISSUE TITLE
Mods cannot replace/extend Global Attributes

### ISSUE THREAD

**Issue by Druark** [KD-lab-Open-Source/Perimeter#159]
When adding GlobalAttributes to the /Scripts folder of a mod, changes made are not applied when the mod is loaded. Trying to extend the file via Extra/ExtraCampaign suffixes does not work either.

It would seem the file is either ignored or base-game overrides it.

This can be confirmed by making a mod which changes the `baseUnitsMax` to any other number, this changes pop cap and would be quickly visible in any mode but instead it remains as default _(250)_ with current behaviour.

**Comment by IonAgorria** [comment]
In docs: "While one can place `Scripts/AttributeLibrary` in mod to replace the existing attribute library, is better to extend it
by creating `Scripts/AttributeLibraryExtra` which will be merged into already loaded attribute library replacing
any existing data. `Scripts/AttributeLibraryExtraCampaign` can also be used to set attributes only when in a campaign
mission. This also applies to RigidBodyPrmLibrary."

Only AttributeLibrary and RigidBodyPrmLibrary can have Extra since they are array based, GlobalAttributes is like a object and harder to "merge", however these are also valid GlobalAttributesCampaign, RigidBodyPrmLibraryCampaign, AttributeLibraryCampaign, I updated the modding docs to specify all possible combinations

Also the bug was fixed, in 3.1.6 it should load properly
