### ISSUE TITLE
Lost synchronization when using scum disruptor

### ISSUE THREAD

**Issue by KBOPYM** [KD-lab-Open-Source/Perimeter#164]
Дважды, за два матча произошла потеря синхронизации в момент атаки Скаморазрушителя.
(Мультиплеер)

**Comment by IonAgorria** [comment]
Cant reproduce firing a scum disruptor on empty area, so seems to be something else involved that actually triggers the desync like unit or building damage. Can you send your CrashDump/desync_... folders? if the host can send it's desync_...._restore even better since contains all logs and copies of each client when desync occurred
